[target.'cfg(target_os = "linux")']
rustflags = [
    "-C", "link-arg=-Wl,--export-dynamic",
]

[target.'cfg(target_os = "macos")']
rustflags = [
    "-C", "link-arg=-Wl,-export_dynamic",
    "-C", "link-arg=-Wl,-stack_size,0x4000000",
    "-C", "force-frame-pointers=yes",
    "-C", "debug-assertions=yes"
]

[target.'cfg(target_os = "windows")']
rustflags = [
    "-C", "link-arg=/EXPORT:bare_init",
]